version: "3.3"
services:
  web:
    container_name: wisen-web
    image: wisen_web
    restart: always
    working_dir: /var/www
    environment:
      TAS_HOST: tas
      TAS_PORT: 9503
    volumes:
      - .:/var/www
    build:
      dockerfile: Dockerfile
      context: .
      args:
        user: van
        uid: 1000
    networks:
      - wisen-net

  tas:
    container_name: wisen-tas
    image: xtrime/telegram-api-server:latest
    restart: always
    environment:
      SERVER_ADDRESS: tas
      SERVER_PORT: 9503
      MEMORY_LIMIT: "256M"
      TIMEZONE: "Asia/Omsk"
      IP_WHITELIST:
      TELEGRAM_API_ID: "20406002"
      TELEGRAM_API_HASH: "2e6fd36a9e30157346f94a3f37eae602"
      VERSION: 1
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wisen
      DB_PASSWORD: wisen
      DB_DATABASE: wisen
      DB_MAX_CONNECTIONS: 10
      DB_IDLE_TIMEOUT: 60
      DB_CACHE_TTL: "+5 minutes"
      HEALTHCHECK_ENABLED: 1
      HEALTHCHECK_INTERVAL: 10
      HEALTHCHECK_REQUEST_TIMEOUT: 20
    working_dir: /var/www/apiserver
    volumes:
      - ./apiserver:/var/www/apiserver
      - ./container/config/tas.php:/var/www/config/tas.php
    entrypoint: php /var/www/apiserver/server.php --docker -s=*
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "2"
    networks:
      - wisen-net

  db:
    container_name: wisen-db
    image: percona:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wisen"
      MYSQL_USER: "wisen"
      MYSQL_PASSWORD: "wisen"
    ports:
      - "3306:3306"
    networks:
      - wisen-net

  redis:
    image: redis:6.2-alpine
    container_name: wisen-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - wisen-net

  adminer:
    image: adminer:latest
    container_name: wisen-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: galkaev
    ports:
      - 8080:8080
    networks:
      - wisen-net
networks:
  wisen-net:
    driver: bridge
