version: "3.3"
services:
  web:
    container_name: wisen-web
    image: wisen_web
    restart: always
    working_dir: /var/www
    environment:
      TAS_HOST: workers
      TAS_PORT: 9503
    volumes:
      - .:/var/www
      - ./submodules:/var/www/submodules
#      - ./storage/logs/supervisor/:/var/log/supervisor/
    build:
      dockerfile: Dockerfile
      context: .
      args:
        user: ${DOCKER_USER}
        uid: ${DOCKER_UID}
        gid: ${DOCKER_GID}
    networks:
      - wisen-net

  workers:
    container_name: wisen-workers
    image: wisen_web
    restart: always
    working_dir: /var/www
    environment:
      TAS_HOST: workers
      TAS_PORT: 9503
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 9503
      MEMORY_LIMIT: "256M"
      TIMEZONE: "Asia/Omsk"
      IP_WHITELIST:
      TELEGRAM_API_ID: "20406002"
      TELEGRAM_API_HASH: "2e6fd36a9e30157346f94a3f37eae602"
      VERSION: 1
      LOGGER_LEVEL: 5
      DB_TYPE: memory
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: "wisen"
      DB_PASSWORD: "wisen"
      DB_DATABASE: "wisen"
      DB_MAX_CONNECTIONS: 10
      DB_IDLE_TIMEOUT: 60
      DB_CACHE_TTL: "+5 minutes"
      HEALTHCHECK_ENABLED: 1
      HEALTHCHECK_INTERVAL: 5
      HEALTHCHECK_REQUEST_TIMEOUT: 5
    entrypoint: supervisord -c /etc/supervisor/conf.d/workers.conf
    volumes:
      - .:/var/www
      - ./submodules/tas:/var/tas
      - ./container/sessions:/var/tas/sessions:rw
      - ./container/supervisor:/etc/supervisor/conf.d
    networks:
      - wisen-net

  db:
    container_name: wisen-db
    image: percona:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wisen"
      MYSQL_USER: "wisen"
      MYSQL_PASSWORD: "wisen"
    ports:
      - "3306:3306"
    networks:
      - wisen-net

  nginx:
    container_name: wisen-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./container/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wisen-net

  redis:
    image: redis:6.2-alpine
    container_name: wisen-redis
    restart: always
    volumes:
      - ./container/data/redis:/data
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - wisen-net

networks:
  wisen-net:
    driver: bridge
